apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubepods
spec:
  replicas: 5
  selector:
    matchlabels:
      type: myapp
  template:
    metadata:
      name: pod1
      labels:
        type: myapp
      spec:
        containers:
        - name: mycontainer
          image: httpd
          ports:
          - containerPort: 80
            name: http

---

apiversion: v1
kind: Service
metadata:
  name: httpservice2
spec:
  type: NodePort
  selector:
    type: httpd
  ports:
  - port: 80
    target: 80
